### ISSUE TITLE
node小白-如何启动项目

### ISSUE THREAD

**Issue by jorry** [lxz612/libcsystem#1]
问下，如何启动改项目，具体步骤是什么，想运行看看，谢谢

**Comment by lxz612** [comment]
要先把Mysql数据表建好，项目里已经有一份数据库的建表文档，可以参照下。建完表，进去config.js修改一下数据库配置，然后npm install，把npm所需的包download下来，最后npm start就可以启动了。 
(PS:我也是从Android转过来的...)

**Comment by jorry** [comment]
项目已经启动了 -_-  现在正在建表中，能留个联系方式么？

**Comment by lxz612** [comment]
嗯，有问题发issue就好了
